// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	   
		int n = Integer.parseInt(args[0]);
		int countUp = 0;
		int countDown = 0;

		for(int i = 0; i < n;  i++) {

			double num = Math.random();

			if (num >= 0.5) {
				
				countUp ++;

			} else {

				countDown ++;

			}

		}

		if (countUp > countDown) {

			double ratio = (double) countDown / countUp;

			System.out.println("> 0.5: " + countDown + " times \n" + "<= 0.5: " + countUp + " times \n" + "Ratio: " + ratio);
			

		} else {

			System.out.println("> 0.5: " + countDown + " times \n" + "<= 0.5: " + countUp + " times");

		}

		

	}
}
